# Generated by Django 5.2.16 on 2026-07-13 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume',
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='staff_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='degree_required',
            field=models.CharField(choices=[('none', 'No degree required'), ('hs', 'High school diploma / GED'), ('associate', 'AA / AS'), ('bachelor', 'BA / BS'), ('master', 'MA / MS'), ('doctorate', 'PhD / Doctorate')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('none', 'No experience required'), ('entry', 'Entry level'), ('mid', 'Mid level'), ('senior', 'Senior level')], default='entry', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('needs_changes', 'Changes requested'), ('viewed', 'Viewed'), ('review', 'Under review'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('part_time', 'Part-time'), ('full_time', 'Full-time'), ('contract', 'Contract'), ('temporary', 'Temporary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('resume', 'Résumé'), ('cover_letter', 'Cover letter'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letter_applications', to='core.studentdocument'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_applications', to='core.studentdocument'),
        ),
    ]
