# Generated by Django 5.2.16 on 2026-07-13 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_address_job_city_job_state_job_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='college_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='is_college',
            field=models.BooleanField(default=False, help_text='Allows school-restricted on-campus postings.'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_on_campus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='target_school',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Primary login/personal email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Current student'), ('alumni', 'Alumni'), ('employer', 'Employer'), ('guest', 'Community guest'), ('staff', 'Career Center Staff')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='announcements/')),
                ('link_url', models.URLField(blank=True)),
                ('school_name', models.CharField(blank=True, help_text='Leave blank to show platform-wide.', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Software Engineering Resume', max_length=120)),
                ('template', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('compact', 'Compact')], default='classic', max_length=20)),
                ('objective', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city_state', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('city_state', models.CharField(blank=True, max_length=120)),
                ('date_from', models.CharField(blank=True, max_length=30)),
                ('date_to', models.CharField(blank=True, max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.resumeprofile')),
            ],
            options={
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=180)),
                ('city_state', models.CharField(blank=True, max_length=120)),
                ('degree', models.CharField(blank=True, max_length=120)),
                ('major', models.CharField(blank=True, max_length=120)),
                ('year_from', models.CharField(blank=True, max_length=10)),
                ('year_to', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_items', to='core.resumeprofile')),
            ],
            options={
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('issuer', models.CharField(blank=True, max_length=150)),
                ('date', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='core.resumeprofile')),
            ],
            options={
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=250)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.resumeprofile')),
            ],
            options={
                'ordering': ['sort_order', '-id'],
            },
        ),
    ]
